package com.renxo.user.utils

interface AppConstants {
    companion object {
        const val IDEAL_TIME: Long = 30 * 60 * 1000L // 30 minutes idle time
    }

    object Preferences {
        const val APP_PREFERENCES = "prefs.preferences_pb"
        const val AUTH_TOKEN = "auth_token"
        const val USER_ID = "user"
        const val EXPIRY_TIMEOUT = "expire_timeout"
        const val MAIN_SERVER_IP = "MainServerIP"
        const val AUTH_SERVER_IP = "AuthServerIP"
        const val DEVICE_ID = "DeviceId"
        const val LANGUAGE_KEY = "selected_language"
        const val CALCULATOR_TYPE_FLOATING = "calculator_type_floating"
        const val DEFAULT_EQUIPMENT = "default_equipment"

    }


    object ReceivingType {
        const val MESSAGE = "message"
        const val RESPONSE = "response"
        const val UI = "UI"


    }

    object Defaults {
        const val PACKING = "packing"
        const val PENDING = "Pending"
        const val CUSTOM_ACTION = "CustomAction"
        const val BUILT_IN = "Built-In"

        const val NEED_REFRESH = "NeedToRefresh"


    }

    object ReceivingActions {
        const val WORKFLOW = "workflow"
    }

    object SendingAction {
        const val CHECK_IN_TRAILER = "CheckInTrailer"
        const val UNLOAD_TRAILER = "UnloadTrailer"
        const val MAIN_MENU = "GetMobileMenu"
        const val START_PALLET_BUILD = "StartPalletBuild"
        const val GENERATE_LPN = "GenerateLPN"
        const val INITIALIZE_PACKING = "InitializePacking"
        const val MODIFY_PACKING = "ModifyPacking"
        const val SUBMIT_WORK_FLOW = "SubmitWorkflow"
        const val VERIFY_ID_FOR_RECEIVING = "VerifyIdForReceiving"
        const val IDENTIFY_INVENTORY = "IdentifyInventory"
        const val VERIFY_LPN_FOR_PACKING = "VerifyLpnForPacking"
        const val SUBMIT_INVENTORY_FOR_RECEIVING = "SubmitInventoryForReceiving"
        const val CHANGE_LANGUAGE = "ChangeLanguage"
        const val LPN_FOR_PALLETS = "ProcessLpnForPallets"
        const val PROCESS_LPN_SUBMISSION = "ProcessLpnSubmission"
        const val CREATE_CARTON = "CreateCarton"
        const val PACK_INVENTORY = "PackInventoryToCarton"
        const val PARTIAL_SUBMIT = "PartialSubmit"
        const val PARTIAL_PICKING_SUBMIT = "PartialPickingSubmit"
        const val SUBMIT_PICKING = "SubmitPicking"
        const val UPDATE_INVENTORY = "UpdateInventoryForPacking"
        const val UNPACK_INVENTORY = "UnpackInventoryToCarton"
        const val RENAME_LPN = "RenameLPN"
        const val CHANGE_OWNERSHIP = "ChangeOwnership"
        const val START_PACKING = "StartPacking"
        const val FIND_WORK = "FindWork"
        const val START_WORK = "StartWork"
        const val DECODE_LPN = "DecodeLpn"
        const val DECODE_SKU = "DecodeSku"
        const val DECODE_LOCATION = "DecodeLocation"
        const val GET_PENDING_TASK_LIST = "ListPendingTask"
        const val GET_ALL_WORK_LIST = "ListAcknowledgedWork"
        const val GET_START_APP_INFO = "StartAppInfo"
        const val INITIALIZE_PICKING = "InitializePicking"
        const val DEPOSIT_INVENTORY = "DepositInventory"
        const val SUBMIT_DEPOSIT = "SubmitDeposit"
        const val LIST_ALL_DEPOSIT_AREAS = "ListAllDepositAreas"
        const val ACCEPT_TASK = "AcceptTask"
        const val CANCEL_WORK = "CancelWork"
        const val CANCEL_TASK = "CancelTask"
        const val GET_EQUIPMENT = "ListEquipment"
        const val GET_WORK_AREAS = "ListWorkArea"
        const val GET_LOCATIONS = "ListLocation"
        const val VALIDATE_TRAILER = "ValidateTrailer"
        const val GET_INVENTORY_BOXES = "ListCartons"
        const val GET_PACKING_INVENTORY = "GetPackingInventory"
        const val WARNING_CONFIRMATION = "WarningConfirmation"

    }

    object EntityNames {
        const val INBOUND_DELIVERY = "inbound_delivery"
        const val LOCATION = "location"
        const val MOBILE_APP_MENU = "mobileapp_menu"
        const val INVENTORY = "inventory"
        const val SEQUENCE = "sequence"
        const val AREA = "area"
        const val TASK = "task2"
        const val LIST_OF_VALUE = "list_of_value"
    }

    object Type {
        const val STAGING = "Staging"
        const val WMS_ACTION = "wms_action"
        const val PROCESSING = "Processing"
    }

    object ErrorCodes {
        const val ERROR = "ERR"
        const val ERR000 = "ERR000"
        const val ERR001 = "ERR001"
        const val ERR002 = "ERR002"
        const val ERR003 = "ERR003"
        const val ERR004 = "ERR004"
        const val ERR005 = "ERR005"
        const val ERR006 = "ERR006"
        const val ERR007 = "ERR007"
        const val ERR104 = "ERR104"
        const val ERR105 = "ERR105"
        const val ERR106 = "ERR106"
        const val ERR107 = "ERR107"
        const val ERR108 = "ERR108"
        const val ERR109 = "ERR109"
        const val ERR110 = "ERR110"
        const val ERR111 = "ERR111"
        const val ERR122 = "ERR122"
        const val ERR123 = "ERR123"
        const val ERR124 = "ERR124"
        const val ERR156 = "ERR156"
        const val ERR158 = "ERR158"
        const val ERR400 = "ERR400"
        const val ERR226 = "ERR226"
        const val ERR232 = "ERR232"
        const val ERR235 = "ERR235"
        const val ERR212 = "ERR212"
        const val ERR217 = "ERR217"
        const val ERR219 = "ERR219"
        const val ERR230 = "ERR230"
        const val ERR231 = "ERR231"
        const val ERR244 = "ERR244"
        const val ERR253 = "ERR253"
        const val ERR255 = "ERR255"
        const val ERR256 = "ERR256"
        const val ERR373 = "ERR373"
        const val ERR374 = "ERR374"
        const val ERR375 = "ERR375"
        const val ERR376 = "ERR376"
        const val ERR377 = "ERR377"
        const val ERR404 = "ERR404"
        const val ERR407 = "ERR407"
        const val ERR408 = "ERR408"
        const val ERR401 = "ERR401"
        const val ERR405 = "ERR405"
        const val ERR402 = "ERR402"
        const val ERR403 = "ERR403"
        const val ERR406 = "ERR406"
        const val ERR409 = "ERR409"
        const val ERR418 = "ERR418"
        const val ERR452 = "ERR452"
        const val ERR457 = "ERR457"
        const val ERR458 = "ERR458"
        const val ERR469 = "ERR469"
        const val ERR470 = "ERR470"
        const val ERR471 = "ERR471"
        const val ERR472 = "ERR472"
        const val ERR473 = "ERR473"
        const val ERR474 = "ERR474"
        const val ERR475 = "ERR475"
        const val ERR476 = "ERR476"
        const val ERR477 = "ERR477"
        const val ERR423 = "ERR423"
        const val ERR479 = "ERR479"
        const val ERR480 = "ERR480"
        const val ERR481 = "ERR481"
        const val ERR482 = "ERR482"
        const val ERR367 = "ERR367"
        const val ERR369 = "ERR369"
        const val ERR483 = "ERR483"
        const val ERR427 = "ERR427"
        const val ERR500 = "ERR500"
        const val ERR501 = "ERR501"
        const val ERR502 = "ERR502"
        const val ERR503 = "ERR503"
        const val ERR504 = "ERR504"
        const val ERR506 = "ERR506"
        const val ERR507 = "ERR507"
        const val ERR509 = "ERR509"
        const val ERR510 = "ERR510"
        const val ERR118 = "ERR118"
        const val ERR511 = "ERR511"
        const val ERR512 = "ERR512"
        const val ERR513 = "ERR513"
        const val ERR514 = "ERR514"
        const val ERR515 = "ERR515"
        const val ERR572 = "ERR572"
        const val ERR545 = "ERR545"
        const val ERR602 = "ERR602"
        const val ERR603 = "ERR603"
        const val ERR604 = "ERR604"
        const val ERR605 = "ERR605"
        const val ERR606 = "ERR606"
        const val ERR607 = "ERR607"
        const val ERR608 = "ERR608"
        const val ERR609 = "ERR609"
        const val ERR610 = "ERR610"
        const val ERR611 = "ERR611"
        const val ERR612 = "ERR612"
        const val ERR617 = "ERR617"
        const val ERR615 = "ERR615"
        const val ERR651 = "ERR651"
        const val ERR657 = "ERR657"
        const val ERR624 = "ERR624"
        const val ERR411 = "ERR411"
        const val ERR758 = "ERR758"
        const val ERR759 = "ERR759"
        const val ERR760 = "ERR760"
        const val ERR766 = "ERR766"
        const val ERR769 = "ERR769"
        const val ERR775 = "ERR775"
        const val ERR851 = "ERR851"
        const val ERR951 = "ERR951"
        const val ERR412 = "ERR412"
        const val ERR420 = "ERR420"
        const val ERR444 = "ERR444"
        const val ERR201 = "ERR201"
        const val ERR4041 = "ERR4041"

    }


    object WarningCodes {


        const val WARNING = "WARN"
        const val LANGUAGE_MISMATCHED = "LanguageMismatched"
        const val WARN000 = "WARN000"
        const val WARN001 = "WARN001"
        const val WARN002 = "WARN002"
        const val WARN003 = "WARN003"
        const val WARN004 = "WARN004"
        const val WARN007 = "WARN007"

    }

    object SuccessCodes {
        const val SUCCESS = "SUCCESS"

        const val SUCCESS000 = "SUCCESS000"
        const val SUCCESS100 = "SUCCESS100"
        const val SUCCESS005 = "SUCCESS005"
        const val SUCCESS002 = "SUCCESS002"
        const val SUCCESS020 = "SUCCESS020"
        const val SUCCESS122 = "SUCCESS122"
        const val SUCCESS199 = "SUCCESS199"
        const val SUCCESS201 = "SUCCESS201"
        const val SUCCESS500 = "SUCCESS500"
        const val SUCCESS220 = "SUCCESS220"
        const val SUCCESS206 = "SUCCESS206"
        const val SUCCESS211 = "SUCCESS211"
        const val SUCCESS323 = "SUCCESS323"
        const val SUCCESS324 = "SUCCESS324"
        const val SUCCESS325 = "SUCCESS325"
        const val SUCCESS326 = "SUCCESS326"
        const val SUCCESS327 = "SUCCESS327"
        const val SUCCESS328 = "SUCCESS328"
        const val SUCCESS329 = "SUCCESS329"
        const val SUCCESS511 = "SUCCESS511"
        const val SUCCESS501 = "SUCCESS501"
        const val SUCCESS522 = "SUCCESS522"
        const val SUCCESS542 = "SUCCESS542"
        const val SUCCESS545 = "SUCCESS545"
        const val SUCCESS546 = "SUCCESS546"
        const val SUCCESS547 = "SUCCESS547"
        const val SUCCESS655 = "SUCCESS655"
        const val SUCCESS656 = "SUCCESS656"
        const val SUCCESS2001 = "SUCCESS2001"
        const val SUCCESS5998 = "SUCCESS5998"
        const val SUCCESS548 = "SUCCESS548"
        const val SUCCESS551 = "SUCCESS551"
        const val SUCCESS555 = "SUCCESS555"
        const val SUCCESS556 = "SUCCESS556"
        const val SUCCESS549 = "SUCCESS549"
        const val SUCCESS1201 = "SUCCESS1201"
        const val SUCCESS1901 = "SUCCESS1901"
        const val SUCCESS1999 = "SUCCESS1999"
        const val SUCCESS2301 = "SUCCESS2301"
        const val SUCCESS1234 = "SUCCESS1234"
        const val SUCCESS1235 = "SUCCESS1235"
        const val SUCCESS1237 = "SUCCESS1237"
        const val SUCCESS1592 = "SUCCESS1592"
        const val SUCCESS1593 = "SUCCESS1593"
        const val SUCCESS1590 = "SUCCESS1590"
        const val SUCCESS1591 = "SUCCESS1591"
        const val SUCCESS1595 = "SUCCESS1595"
        const val SUCCESS1594 = "SUCCESS1594"
        const val SUCCESS552 = "SUCCESS552"
        const val SUCCESS553 = "SUCCESS553"
        const val SUCCESS558 = "SUCCESS558"
        const val SUCCESS554 = "SUCCESS554"
        const val SUCCESS557 = "SUCCESS557"
        const val MULTIPLE_IBD_FOUND = "MULTIPLE_IBD_FOUND"
        const val MULTIPLE_ORDERS_FOUND = "MULTIPLE_ORDERS_FOUND"

    }


    object Params {
        const val workarea = "workarea"
        const val lpn_ids = "lpn_ids"
        const val entityName = "entityName"
        const val attribute_name = "attribute_name"
        const val id_fields = "id_fields"
        const val others = "others"
        const val quantityForFrontend = "quantityForFrontend"
        const val quantity = "quantity"
        const val inventory = "inventory"
        const val areas = "area"
        const val task_id_list = "task_id_list"
        const val workflow = "workflow"
        const val result = "result"
        const val jwt_language = "jwt_language"
        const val db_language = "db_language"
        const val travel_sequence = "travel_sequence"
        const val all = "all"
        const val next_hop = "next_hop"
        const val multiple_ibds = "multiple_ibds"
        const val multiple_orders = "multiple_orders"
        const val order = "order"
        const val attributes = "attributes"
        const val lpn = "lpn"
        const val PACKING_LOCATION = "packing_location"
        const val language_id = "new_language"
        const val box_lpn = "box_lpn"
        const val transport_equipment = "transport_equipment"
        const val location = "location"
        const val area = "area"
        const val tasks = "tasks"
        const val dock = "dock"
        const val type = "type"
        const val ibd = "ibd"
        const val sku = "sku"
        const val to_lpn = "to_lpn"
        const val available_pallets = "available_pallets"
        const val created_lpn = "created_lpn"
        const val fields = "fields"
        const val suggested_box = "suggested_boxes"
        const val operation = "operation"
        const val isBox = "isBox"
        const val user = "user"
        const val users = "users"
        const val library = "library"
        const val action = "action"
        const val function = "function"
        const val message = "message"
        const val transportEquipment = "transportEquipment"
        const val warning_ID = "warning_ID"
        const val new_next_hop = "new_next_hop"
        const val error = "error"
        const val inboundDelivery = "inboundDelivery"
        const val primaryKey = "primaryKey"
        const val locationType = "locationType"
        const val source_lpn = "source_lpn"
        const val target_lpn = "target_lpn"
        const val update_duplicate = "update_duplicate"
        const val update = "update"
        const val ownership = "ownership"
        const val from_area = "from_area"
        const val default_area = "default_area"
        const val compatible_task = "compatible_task"
        const val is_tasks_exists = "is_tasks_exists"
        const val equipment = "equipment"
        const val current_location = "current_location"
        const val code = "code"
        const val filter = "filter"
        const val value = "value"
        const val group_type = "group_type"
        const val status = "status"
        const val task_group_id = "task_group_id"
        const val original_id = "original_id"
        const val id = "id"
        const val box_id = "box_id"
        const val inv_detail_id = "inv_detail_id"
        const val task_id = "task_id"
        const val use_compatibility_type = "use_compatibility_type"
        const val allocation_id = "allocation_id"
        const val product_id = "product_id"
        const val custom_fields = "custom_fields"
        const val pack = "pack"
        const val inv_src_id = "inv_src_id"
        const val sub_lpn = "sub_lpn"
        const val source_Id = "source_id"
        const val packing_Location = "packing_location"

    }

    object ResponseVariables {
        const val user = "{user}"
        const val users = "{users}"
        const val entityName = "{entityName}"
        const val library = "{library}"
        const val action = "{action}"
        const val function = "{function}"
        const val transportEquipment = "{transportEquipment}"
        const val error = "{error}"
        const val inboundDelivery = "{inboundDelivery}"
        const val lpn = "{lpn}"
        const val primaryKey = "{primaryKey}"
        const val locationType = "{locationType}"
        const val dock = "{dock}"
        const val ibd = "{ibd}"
        const val created_lpn = "{created_lpn}"
        const val update = "{update}"
        const val ownership = "{ownership}"
        const val location = "{location}"
    }


}